name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
        
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x        

      - run: |
          npm install
      - run: |
          npm run all
        
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: ./
        id: get_version
        with:
          project: ./package.json
        
      - name: log
        run: |
          echo "version:      ${{ steps.get_version.outputs.version }}"
          echo "major:        ${{ steps.get_version.outputs.major }}"
          echo "minor:        ${{ steps.get_version.outputs.minor }}"
          echo "patch:        ${{ steps.get_version.outputs.patch }}"
          echo "pre-release:  ${{ steps.get_version.outputs.pre-release }}"
          echo "build:        ${{ steps.get_version.outputs.build }}"

          
